# Habumi is free software and will stay that way. There is nothing behind this
# button that you do not already have: no extra features, no private builds, no
# support tier. It is here because the project costs time, and some people
# prefer to say thank you with more than words.
github: [Goribesh]
ko_fi: godziller
